### ISSUE TITLE
컨피그를 ini 말고 json으로 하는건 어떨까요?

### ISSUE THREAD

**Issue by Hoto-Cocoa** [MuhunKim/commit-telegram-bot#4]

**Comment by MuhunKim** [comment]
처음에 json으로 할려 했으나 [json 레퍼런스가 난해하게 느껴져](https://docs.python.org/3/library/json.html) ini 쪽이 더 편하게 느껴져 골랐습니다

하지만 [메인 코드를 보셨다면]  ini 파서 모듈이 뻑나가서 주석처리 후 임시로 하드코딩로 사용자 정보가 입력된 상태임을 알수 있으실 겁니다. ~~그리고 현재 이 레포는 방치된 상태입니다~~

요즘 한가해서 하드코딩 된 부분을 지워버릴까 고려 중 이였는데, 의견 주셔서 감사합니다. 

추후 json으로 파서를 바꿔보겠습니다.

**Comment by Hoto-Cocoa** [comment]
JSON으로 하신다면 도움을 드릴 수 있을것 같네요

**Comment by MuhunKim** [comment]
PR이라면 언제든지 환영합니다 ㅎㅎ 👍

**Comment by MuhunKim** [comment]
#5 PR 진행 중

**Comment by MuhunKim** [comment]
이슈 닫음
